# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:
    # The "android/android" uses a medium resource
    executor:
      name: android/android

    steps:
      - checkout
      - android/run-tests:
          test-command: ./gradlew testDebug

workflows:
  debug:
    jobs:
      - build-and-test
