# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:  
    # These next lines define the Android machine image executor: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android/android-machine

    # TODO: Add linter
    steps:
      - checkout
      - android/run-tests:
          test-command: ./gradlew testDebug

workflows:
  sample: 
    jobs:
      - build-and-test
